name: ci
on:
  push:
    branches:
      - beta
  schedule:
    - cron: "0 12 * * *"
jobs:
  tests:
    runs-on: ubuntu-18.04
    name: test
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        ref: beta
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements/requirements.txt
          pip install --no-cache-dir -r requirements/requirements-extra.txt
          pip install --no-cache-dir -r requirements/requirements-dev.txt
          pip install requests
      - name: black linter
        run: |
          black . --check
      # - name: mypy checker
      #   run: |
      #     mypy tensorcircuit
      # - name: pylint checker
      #   run: |
      #     pylint tensorcircuit tests
      # - name: test scripts
      #   run: |
      #     pytest --cov=tensorcircuit --cov-report=xml -svv --benchmark-skip
      # - name: run example demos
      #   run: |
      #     cd examples
      #     python mcnoise_check.py
      #     python vqnhe_h6.py
      #     python qaoa_dqas.py
      #     python mcnoise_boost.py
      #     python quantumng.py
      #     python universal_lr.py
      - name: setup build
        run: |
          python3 .github/nightly_build/darkify.py
          python3 setup.py bdist_wheel sdist
      - name: upload to pypi
        # if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # skip_existing: true
